export * from './types'
export { analyserDocument, serialiserDocument } from './dom'
export { analyserGabarit, ErreurGabarit } from './gabarit/analyse'
export { verifierDepot } from './gabarit/verification'

export function versionMoteur(): string {
  return '1.0.0'
}
export { remplirTextes } from './gabarit/remplissage'
export { ajusterAuCadre, ajusterDocument, PLANCHER_ECHELLE } from './gabarit/ajustement'
export { CataloguePolices, chargerPolicesDepuisDossier } from './rendu/polices'
export type { PoliceChargee } from './rendu/polices'
export { calculerPlacement, insererPhoto, retirerZonePhoto } from './gabarit/photo'
export type { Photo } from './gabarit/photo'
export { apposerFiligrane } from './gabarit/filigrane'
export { dimensionnerRacine, dimensionsPhysiques, pixelsPourDpi, proportions, rendrePng, DPI_LIVRAISON } from './rendu/png'
export type { DimensionsPhysiques, OptionsPng } from './rendu/png'
export { rendreWebp, QUALITE_PAR_DEFAUT } from './rendu/webp'
export type { OptionsWebp } from './rendu/webp'
export { vectoriserTextes } from './gabarit/vectorisation'
export type { ResultatVectorisation } from './gabarit/vectorisation'
export { rendrePdf } from './rendu/pdf'
export { composerCarte } from './composition'
export type { CarteComposee, DemandeComposition } from './composition'
